services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sati_backend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=4000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sati_frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend
